project_id = "qwrkaktntdjsulthaask"

[functions.chat-assistant]
verify_jwt = false

[functions.ai-image-generator]
verify_jwt = false

[functions.ai-policy-analyzer]
verify_jwt = false

[functions.terminal-scraper]
verify_jwt = false

[functions.terminal-api-proxy]
verify_jwt = false

[functions.terminal-21st-magic]
verify_jwt = false